apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: ap-be-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tech@creatory.id
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx